# Workaround until https://pagure.io/koji/pull-request/2151 is released
# in Koji v1.22

- name: determine expected koji-gc checksum
  set_fact:
    expected_koji_gc_checksum: "f343e6fd524918f1edffbae650cdd9244585d29b"

- name: determine expected koji-gc checksum for py3
  set_fact:
    expected_koji_gc_checksum: "60e14bf738d9f6b7b9bd9a917d4221b9033895b5"
  when:
    - ansible_distribution_file_variety == "RedHat"
    - ansible_distribution_major_version|int > 7

- name: discover checksum for koji-gc
  stat:
    path: /usr/sbin/koji-gc
  register: koji_gc

- name: update koji-gc for GSSAPI
  get_url:
    url: https://pagure.io/koji/raw/master/f/util/koji-gc
    dest: /usr/sbin/koji-gc
    checksum: "sha1:f343e6fd524918f1edffbae650cdd9244585d29b"
    owner: root
    group: root
    mode: 0755
  when: koji_gc.stat.checksum != expected_koji_gc_checksum

- name: use python3 for /usr/sbin/koji-gc
  lineinfile:
    dest: /usr/sbin/koji-gc
    regexp: '^#!/usr/bin/python2'
    line: "#!/usr/bin/python3"
  when: ansible_distribution_file_variety == "RedHat" and ansible_distribution_major_version|int > 7
