# Workaround until https://pagure.io/koji/pull-request/2151 is released
# in Koji v1.22

- name: update koji-gc for GSSAPI
  get_url:
    url: https://pagure.io/koji/raw/master/f/util/koji-gc
    dest: /usr/sbin/koji-gc
    checksum: "sha1:773eb914d128b41f39e42a09735fd1cbf4b43230"
    owner: root
    group: root
    mode: 0755

- name: use python3 for /usr/sbin/koji-gc
  lineinfile:
    dest: /usr/sbin/koji-gc
    regexp: '^#!/usr/bin/python2'
    line: "#!/usr/bin/python3"
  when: ansible_distribution_file_variety == "RedHat" and ansible_distribution_major_version|int > 7
