- name: Disable SELinux
  selinux:
    policy: targeted
    state: permissive

- name: Install Koji packages
  package:
    name:
    - postgresql-server
    - koji-hub
    - mod_ssl
    - mod_auth_gssapi
    state: present

- name: initialize postgresql
  command: postgresql-setup initdb
  args:
    creates: /var/lib/pgsql/data/pg_hba.conf
  notify:
  - restart postgresql

- name: configure pg_hba.conf
  copy:
    dest: /var/lib/pgsql/data/pg_hba.conf
    content: |
      local   koji        koji                       trust
      local   all         postgres                   peer
  notify:
  - restart postgresql

- name: disable TCP/IP for postgres
  lineinfile:
    dest: /var/lib/pgsql/data/postgresql.conf
    regexp: '^#listen_addresses'
    line: "listen_addresses = ''"
  notify:
  - restart postgresql

- name: start postgresql
  service:
    name: postgresql
    state: started
    enabled: true

- name: create koji user
  user:
    name: koji
    shell: /bin/bash

- name: create postgres user koji
  postgresql_user:
    name: koji
    password: test
    #priv: "CONNECT/koji:ALL"
    #login_unix_socket: /var/run/postgresql
  become_user: postgres

- name: create postgres koji database
  postgresql_db:
    name: koji
    owner: koji
    #login_unix_socket: /var/run/postgresql
  become_user: postgres

- name: check if database for app needs populating
  postgresql_query:
    db: koji
    login_user: koji
    query: SELECT COUNT(*) FROM permissions;
  become_user: koji
  ignore_errors: true
  register: database_is_populated

- name: populate the koji database
  shell: psql koji koji < /usr/share/doc/koji*/docs/schema.sql
  args:
    executable: /bin/bash
  when: database_is_populated.failed
  become_user: koji

- name: insert kdreyer as a user
  postgresql_query:
    db: koji
    login_user: koji
    query: "INSERT INTO users (name, status, usertype) VALUES ('kdreyer', 0, 0);"
  when: database_is_populated.failed
  become_user: koji

- name: grant kdreyer admin rights
  postgresql_query:
    db: koji
    login_user: koji
    query: "INSERT INTO user_perms (user_id, perm_id, creator_id) VALUES (1, 1, 1);"
  when: database_is_populated.failed
  become_user: koji

- name: grant apache read access to HTTP keytab
  file:
    path: /var/local/HTTP.kojidev.example.com.keytab
    owner: root
    group: apache
    mode: 0640
  notify:
  - restart httpd

- name: copy mod_ssl config
  copy:
    src: files/ssl.conf
    dest: /etc/httpd/conf.d/ssl.conf
    owner: root
    group: root
    mode: 0644
  notify:
  - restart httpd

- name: copy /etc/httpd/conf.d/kojihub.conf
  copy:
    src: files/kojihub.conf
    dest: /etc/httpd/conf.d/kojihub.conf
    owner: root
    group: root
    mode: 0644
  notify:
  - restart httpd

- name: copy /etc/koji-hub/hub.conf
  copy:
    src: files/hub.conf
    dest: /etc/koji-hub/hub.conf
    owner: root
    group: root
    mode: 0644
  notify:
  - restart httpd

- name: start httpd
  service:
    name: httpd
    enabled: true
    state: started

- name: /mnt/koji directories
  file:
    path: /mnt/koji/{{ item }}
    state: directory
    mode: 0755
    owner: apache
    group: apache
  with_items:
    -
    - packages
    - repos
    - work
    - scratch
    - repos-dist

- name: Configure the new builder on the hub
  koji_host:
    koji: kojidev
    name: kojidev.example.com
    arches: [x86_64]
    state: enabled
    channels:
    - default
    - createrepo
  become: no

- name: Configure the kojira user account
  koji_user:
    koji: kojidev
    name: koji/kojira
    state: enabled
    permissions:
    - repo
  become: no

- name: Configure the garbagecollector user account
  koji_user:
    koji: kojidev
    name: koji/garbagecollector
    state: enabled
    permissions:
    - admin
  become: no

- name: trashcan tag
  koji_tag:
    koji: kojidev
    name: trashcan
  become: no
